### ISSUE TITLE
I can't use get_dm_history()

### ISSUE THREAD

**Issue by matteokocken** [d60/twikit#112]
Do you know why i have this error ? 

```
 dms = user.get_dm_history()
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matte\AppData\Local\Programs\Python\Python312\Lib\site-packages\twikit\user.py", line 474, in get_dm_history
    return self._client.get_dm_history(self.id, max_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matte\AppData\Local\Programs\Python\Python312\Lib\site-packages\twikit\client.py", line 3670, in get_dm_history
    items = response['conversation_timeline']['entries']
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'entries'
```

With this code 
```
# Initialize client
client = Client('fr-FR')

if os.path.exists('cookies.json'):
    client.load_cookies('cookies.json')
else:
    client.login(
        auth_info_1=USERNAME,
        auth_info_2=EMAIL,
        password=PASSWORD
    )
    client.save_cookies('cookies.json')

user = client.get_user_by_screen_name(USERNAME)
# Get all message
dms = user.get_dm_history()

print(dms)
```

**Comment by d60** [comment]
@matteokocken 
fixed in version 1.7.2

**Comment by glandium** [comment]
This is still happening because the code does this:
https://github.com/d60/twikit/blob/f2658402d93a2bb0050e1ceea3c6cbaf0053ba41/twikit/client/client.py#L3042-L3044
That is, it's getting the entries before checking the key is in the dict.

**Comment by RetakerMZ** [comment]
> This is still happening because the code does this:
> 
> https://github.com/d60/twikit/blob/f2658402d93a2bb0050e1ceea3c6cbaf0053ba41/twikit/client/client.py#L3042-L3044
> 
> 
> That is, it's getting the entries before checking the key is in the dict.

it seems like the entries field is completely removed from twitter ? maybe its a new update
